#!/usr/bin/env python3
"""Regenerate QUERIES.md from the dashboard JSONs in grafana-dashboards/.

The dashboards' `expr` fields are the single source of truth for every PromQL/LogQL query the
monitoring stack uses; QUERIES.md is the greppable index of them (Phase 9c's bench-run.sh reuses
these queries against the Prometheus range API). Run after any dashboard edit/export:

    python3 k8s/monitoring/extract-queries.py
"""
import json
import os

DIR = os.path.dirname(os.path.abspath(__file__))
ORDER = ["overview", "cluster-overview", "app-red", "errors-and-problems", "database",
         "rabbitmq", "minio", "hpa-scaling", "forum-business"]

HEADER = """# Dashboard queries (generated by extract-queries.py — do not edit by hand)

Every query used by the Phase 10c Grafana dashboards, extracted from the JSON files in
`grafana-dashboards/` — **those JSONs' `expr` fields are the single source of truth**; this file
exists so Phase 9c's `bench-run.sh` (and any grep) can find the exact PromQL/LogQL without
reverse-engineering dashboard JSON. Regenerate after editing a dashboard:

```bash
python3 k8s/monitoring/extract-queries.py
```

Notes for benchmark scripting:
- `$__rate_interval` is a Grafana macro — replace with a literal window (e.g. `[1m]`) when
  querying the Prometheus HTTP API directly.
- `job="backend"` is the Service name (ServiceMonitor-derived), stable across replicas.
- Queries against `forum_*` series return empty (not zero) until the counter's first increment.
"""


def main() -> None:
    out = [HEADER]
    for name in ORDER:
        path = os.path.join(DIR, "grafana-dashboards", f"{name}.json")
        with open(path) as fh:
            d = json.load(fh)
        out.append(f"\n## {d['title']}  (`{name}.json`, uid `{d['uid']}`)\n")
        for panel in d["panels"]:
            if panel["type"] == "row":
                out.append(f"\n### {panel['title']}\n")
                continue
            out.append(f"**{panel['title']}** ({panel['type']})\n")
            for tgt in panel.get("targets", []):
                expr = tgt.get("expr", "")
                if not expr:
                    continue
                lang = "logql" if tgt.get("datasource", {}).get("type") == "loki" else "promql"
                legend = tgt.get("legendFormat")
                suffix = f"   # {legend}" if legend and "{{" not in legend else ""
                out.append(f"```{lang}\n{expr}{suffix}\n```\n")
        for ann in d.get("annotations", {}).get("list", []):
            if ann.get("expr"):
                out.append(f"**Annotation: {ann['name']}**\n```promql\n{ann['expr']}\n```\n")

    target = os.path.join(DIR, "QUERIES.md")
    with open(target, "w") as fh:
        fh.write("\n".join(out))
    print(f"QUERIES.md written ({len(out)} blocks)")


if __name__ == "__main__":
    main()
