// <auto-generated />
using System;
using Forum.Modules.Content.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forum.Modules.Content.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260701211425_InitialContent")]
    partial class InitialContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("forum_content")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forum.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_on_utc");

                    b.ToTable("outbox_messages", "forum_content");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Categories.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("IconFileId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("icon_file_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", "forum_content");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Comments.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("owner_id");

                    b.Property<string>("ParentId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(161)
                        .IsUnicode(false)
                        .HasColumnType("character varying(161)")
                        .HasColumnName("path");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_comments_parent_id");

                    b.HasIndex("ThreadId", "Path")
                        .HasDatabaseName("ix_comments_thread_path");

                    b.ToTable("comments", "forum_content");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Threads.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", "forum_content");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Threads.Thread", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("category_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_threads");

                    b.HasIndex("CategoryId", "IsPinned", "CreatedOnUtc", "Id")
                        .IsDescending(false, true, true, true)
                        .HasDatabaseName("ix_threads_feed")
                        .HasFilter("is_deleted = false");

                    b.ToTable("threads", "forum_content");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Threads.ThreadTag", b =>
                {
                    b.Property<string>("ThreadId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("thread_id");

                    b.Property<string>("TagId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("tag_id");

                    b.HasKey("ThreadId", "TagId")
                        .HasName("pk_thread_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_thread_tags_tag_id");

                    b.ToTable("thread_tags", "forum_content");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Comments.Comment", b =>
                {
                    b.HasOne("Forum.Modules.Content.Domain.Comments.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_comments_comments_parent_id");

                    b.HasOne("Forum.Modules.Content.Domain.Threads.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_threads_thread_id");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Threads.Thread", b =>
                {
                    b.HasOne("Forum.Modules.Content.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_threads_categories_category_id");
                });

            modelBuilder.Entity("Forum.Modules.Content.Domain.Threads.ThreadTag", b =>
                {
                    b.HasOne("Forum.Modules.Content.Domain.Threads.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thread_tags_tags_tag_id");

                    b.HasOne("Forum.Modules.Content.Domain.Threads.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thread_tags_threads_thread_id");
                });
#pragma warning restore 612, 618
        }
    }
}
