// <auto-generated />
using System;
using Forum.Modules.Social.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forum.Modules.Social.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SocialDbContext))]
    partial class SocialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("forum_social")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forum.Infrastructure.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "forum_social");
                });

            modelBuilder.Entity("Forum.Infrastructure.Messaging.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_on_utc");

                    b.ToTable("outbox_messages", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Conversations.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DirectKey")
                        .HasMaxLength(53)
                        .IsUnicode(false)
                        .HasColumnType("character varying(53)")
                        .HasColumnName("direct_key");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasIndex("DirectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_conversations_direct_key")
                        .HasFilter("direct_key IS NOT NULL");

                    b.ToTable("conversations", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Conversations.ConversationParticipant", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<DateTimeOffset>("JoinedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_on_utc");

                    b.Property<DateTimeOffset?>("LastReadOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_on_utc");

                    b.Property<DateTimeOffset?>("LeftOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_on_utc");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("pk_conversation_participants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_conversation_participants_user");

                    b.ToTable("conversation_participants", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Conversations.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<DateTimeOffset?>("EditedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_on_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ConversationId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_history");

                    b.ToTable("messages", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Friendships.Friendship", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_on_utc");

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("addressee_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("AddresseeId")
                        .HasDatabaseName("ix_friendships_addressee");

                    b.HasIndex("RequesterId")
                        .HasDatabaseName("ix_friendships_requester");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique()
                        .HasDatabaseName("ux_friendships_pair_directed");

                    b.ToTable("friendships", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Friendships.SocialBlock", b =>
                {
                    b.Property<string>("BlockerId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("blocker_id");

                    b.Property<string>("BlockedId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("blocked_id");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.HasKey("BlockerId", "BlockedId")
                        .HasName("pk_social_blocks");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_social_blocks_blocked");

                    b.ToTable("social_blocks", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Groups.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("owner_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("Id")
                        .IsDescending()
                        .HasDatabaseName("ix_groups_public_directory")
                        .HasFilter("visibility = 'public' AND is_deleted = false");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_groups_owner");

                    b.ToTable("groups", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Groups.GroupInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("group_id");

                    b.Property<string>("InvitedBy")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("invited_by");

                    b.Property<string>("InvitedUserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("invited_user_id");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_group_invites");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_group_invites_inviter");

                    b.HasIndex("InvitedUserId")
                        .HasDatabaseName("ix_group_invites_invitee");

                    b.HasIndex("GroupId", "InvitedUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_group_invites_pending");

                    b.ToTable("group_invites", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Groups.GroupMembership", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("group_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.Property<string>("InvitedBy")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("invited_by");

                    b.Property<DateTimeOffset>("JoinedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_on_utc");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_memberships");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_memberships_user");

                    b.ToTable("group_memberships", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Notifications.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("TargetId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("target_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_unread")
                        .HasFilter("is_read = false");

                    b.HasIndex("UserId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_notifications_feed");

                    b.ToTable("notifications", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Presence.UserPresence", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("LastHeartbeatOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_on_utc");

                    b.HasKey("UserId")
                        .HasName("pk_user_presence");

                    b.ToTable("user_presence", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Privacy.UserPrivacySettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.Property<string>("FriendRequests")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("friend_requests");

                    b.Property<string>("GroupInvites")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("group_invites");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("messages");

                    b.Property<bool>("ShowOnlineStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("show_online_status");

                    b.HasKey("UserId")
                        .HasName("pk_user_privacy_settings");

                    b.ToTable("user_privacy_settings", "forum_social");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Conversations.ConversationParticipant", b =>
                {
                    b.HasOne("Forum.Modules.Social.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_participants_conversations_conversation_id");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Conversations.Message", b =>
                {
                    b.HasOne("Forum.Modules.Social.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_conversation_id");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Groups.GroupInvite", b =>
                {
                    b.HasOne("Forum.Modules.Social.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_invites_groups_group_id");
                });

            modelBuilder.Entity("Forum.Modules.Social.Domain.Groups.GroupMembership", b =>
                {
                    b.HasOne("Forum.Modules.Social.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_memberships_groups_group_id");
                });
#pragma warning restore 612, 618
        }
    }
}
